services:

  postgres:
    image: postgres:16-alpine
    container_name: mobiflow_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/01_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  ingestion:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    container_name: mobiflow_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      FLASK_PORT: ${FLASK_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  dbt:
    build:
      context: ./analytics/dbt
      dockerfile: Dockerfile
    container_name: mobiflow_dbt
    env_file:
      - .env
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DBT_SCHEMA: ${DBT_SCHEMA:-analytics}
      DBT_THREADS: ${DBT_THREADS:-1}
    volumes:
      - ./analytics/dbt:/usr/app/dbt
    depends_on:
      postgres:
        condition: service_healthy
    command: ["debug"]

volumes:
  postgres_data:
