name: mobiflow_analytics
version: "1.0.0"
config-version: 2

profile: mobiflow

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]

clean-targets:
  - target
  - dbt_packages
  - logs

models:
  mobiflow_analytics:
    +materialized: view
    staging:
      +materialized: view
      +tags: ["staging"]
    marts:
      +materialized: view
      +tags: ["mart"]
